name: minesweeper
description: Minesweeper project for learning flutter, written as fast as possible then improved later.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.3
  universal_html: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  fonts:
   - family:  NavalMine
     fonts:
      - asset: fonts/NavalMine.ttf
  uses-material-design: true

flutter_icons:
  image_path: 'fonts/naval_mine.png'
  android: true
  ios: true
  remove_alpha_ios: true